version: '3'
services:
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    env_file: ./.env

  flask:
    restart: always
    image: backend-flask
    build:
      args:
        - DB_CONN_STRING=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432
      context: ./server
    entrypoint: /app/entrypoint.sh
    ports:
      - 5000:5000

  vue:
    image: frontend-vue
    build:
      args:
        - API_BASE_URL=$API_BASE_URL
      context: ./client
    ports:
      - 8080:80