version: '3'
services:
  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file: ./.env

  flask:
    image: backend-flask
    build:
      context: ./server
    entrypoint: /app/entrypoint.sh
    ports:
      - 5000:5000

  vue:
    image: frontend-vue
    build:
      args:
        - API_BASE_URL=${API_BASE_URL}
      context: ./client
    ports:
      - 8080:80